#!/bin/bash
while true
do
	echo "Running..."
	docker container prune -f
	docker volume prune -f
	docker image prune -f
	docker system prune -af
	echo "...done"
	echo ">>> sleeping for 1 hour"
	echo ""
	sleep 3600

done
